import React, { useRef } from "react";
import { motion } from "framer-motion";
import html2canvas from "html2canvas";

type Props = {
  dnaData: {
    inputs: {
      favActor: string;
      favMusic: string;
      favCuisine: string;
      favCity: string;
    };
    results: any[];
    insights: { [key: string]: any[] };
  };
};

export default function DNAExporter({ dnaData }: Props) {
  const exportRef = useRef<HTMLDivElement>(null);

  const handleExportImage = async () => {
    if (!exportRef.current) return;

    try {
      const canvas = await html2canvas(exportRef.current, {
        backgroundColor: '#000000',
        scale: 2,
        useCORS: true,
      });

      const link = document.createElement('a');
      link.download = 'cultural-dna-profile.png';
      link.href = canvas.toDataURL();
      link.click();
    } catch (error) {
      console.error('Export failed:', error);
      alert('Export failed. Please try again.');
    }
  };

  const handleShareProfile = () => {
    const profileText = `🧬 My Cultural DNA Profile:
🎭 Actor: ${dnaData.inputs.favActor}
🎵 Music: ${dnaData.inputs.favMusic}
🍽 Cuisine: ${dnaData.inputs.favCuisine}
🌆 City: ${dnaData.inputs.favCity}

Generated with Cultural DNA Explorer!`;

    if (navigator.share) {
      navigator.share({
        title: 'My Cultural DNA Profile',
        text: profileText,
      });
    } else {
      navigator.clipboard.writeText(profileText);
      alert('Profile copied to clipboard!');
    }
  };

  const getTotalInsights = () => {
    return Object.values(dnaData.insights).reduce((total, insights) => total + insights.length, 0);
  };

  return (
    <div className="space-y-6">
      {/* Export Preview */}
      <div 
        ref={exportRef}
        className="bg-gradient-to-br from-gray-900 via-black to-gray-900 border border-cyan-500/30 rounded-lg p-8 max-w-2xl mx-auto"
      >
        <div className="text-center mb-6">
          <h2 className="text-3xl font-bold bg-gradient-to-r from-pink-500 via-purple-500 to-cyan-500 bg-clip-text text-transparent mb-2">
            🧬 CULTURAL DNA PROFILE
          </h2>
          <div className="text-cyan-400 text-sm">Neural Taste Analysis Complete</div>
        </div>

        <div className="grid grid-cols-2 gap-4 mb-6">
          <div className="space-y-3">
            <div className="flex items-center space-x-2">
              <span className="text-pink-400">🎭</span>
              <span className="text-white text-sm">{dnaData.inputs.favActor || 'Not specified'}</span>
            </div>
            <div className="flex items-center space-x-2">
              <span className="text-purple-400">🎵</span>
              <span className="text-white text-sm">{dnaData.inputs.favMusic || 'Not specified'}</span>
            </div>
          </div>
          <div className="space-y-3">
            <div className="flex items-center space-x-2">
              <span className="text-orange-400">🍽</span>
              <span className="text-white text-sm">{dnaData.inputs.favCuisine || 'Not specified'}</span>
            </div>
            <div className="flex items-center space-x-2">
              <span className="text-cyan-400">🌆</span>
              <span className="text-white text-sm">{dnaData.inputs.favCity || 'Not specified'}</span>
            </div>
          </div>
        </div>

        <div className="border-t border-gray-700 pt-4">
          <div className="text-center">
            <div className="text-green-400 text-lg font-bold">{getTotalInsights()}</div>
            <div className="text-gray-400 text-xs">CULTURAL CONNECTIONS DISCOVERED</div>
          </div>
        </div>

        <div className="text-center mt-4 text-xs text-gray-500">
          Generated by Cultural DNA Explorer v2.0
        </div>
      </div>

      {/* Export Controls */}
      <div className="flex justify-center space-x-4">
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={handleExportImage}
          className="bg-gradient-to-r from-green-600 to-cyan-600 hover:from-green-500 hover:to-cyan-500 text-white px-6 py-3 rounded-lg font-semibold transition-all duration-300 shadow-lg shadow-green-500/25"
        >
          📸 EXPORT IMAGE
        </motion.button>

        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={handleShareProfile}
          className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white px-6 py-3 rounded-lg font-semibold transition-all duration-300 shadow-lg shadow-purple-500/25"
        >
          🔗 SHARE PROFILE
        </motion.button>
      </div>

      <div className="text-center text-gray-400 text-sm">
        Share your cultural DNA with friends or save it for future reference
      </div>
    </div>
  );
}